export const budgetConstants = {

    REQUEST_ACTUAL_FOR_BUDGET: 'REQUEST_ACTUAL_FOR_BUDGET',
    SET_ACTUAL_FOR_BUDGET: 'SET_ACTUAL_FOR_BUDGET',
    CLEAR_ACTUAL_FOR_BUDGET: 'CLEAR_ACTUAL_FOR_BUDGET',

    REQUEST_BUDGET_TEMPLATE: 'REQUEST_BUDGET_TEMPLATE',
    SET_BUDGET_TEMPLATE: 'SET_BUDGET_TEMPLATE',
    CLEAR_BUDGET_TEMPLATE: 'CLEAR_BUDGET_TEMPLATE',

    REQUEST_PROJECTS_BUDGET_LIST: 'REQUEST_PROJECTS_BUDGET_LIST',
    SET_PROJECTS_BUDGET_LIST: 'SET_PROJECTS_BUDGET_LIST',
    CLEAR_PROJECTS_BUDGET_LIST: 'CLEAR_PROJECTS_BUDGET_LIST',

    REQUEST_BUDGET_ACTUAL_LIST: 'REQUEST_BUDGET_ACTUAL_LIST',
    REQUEST_SAVE_BUDGET_LIST: 'REQUEST_SAVE_BUDGET_LIST',
    SET_BUDGET_ACTUAL_LIST: 'SET_BUDGET_ACTUAL_LIST',
    CLEAR_BUDGET_ACTUAL_LIST: 'CLEAR_BUDGET_ACTUAL_LIST',
};
