export const cariReportConstants = {
    REQUEST_CARI_REPORT_TITLES: 'REQUEST_CARI_REPORT_TITLES',
    SET_CARI_REPORT_TITLES: 'SET_CARI_REPORT_TITLES',
    CLEAR_CARI_REPORT_TITLES: 'CLEAR_CARI_REPORT_TITLES',

    REQUEST_CARI_REPORT_SUB_GROUP: 'REQUEST_CARI_REPORT_SUB_GROUP',
    SET_CARI_REPORT_SUB_GROUP: 'SET_CARI_REPORT_SUB_GROUP',
    CLEAR_CARI_REPORT_SUB_GROUP: 'CLEAR_CARI_REPORT_SUB_GROUP',

    REQUEST_CARI_REPORT_SUB_GROUP_DETAIL: 'REQUEST_CARI_REPORT_SUB_GROUP_DETAIL',
    SET_CARI_REPORT_SUB_GROUP_DETAIL: 'SET_CARI_REPORT_SUB_GROUP_DETAIL',
    CLEAR_CARI_REPORT_SUB_GROUP_DETAIL: 'CLEAR_CARI_REPORT_SUB_GROUP_DETAIL',

    REQUEST_CARI_REPORT_SUB_GROUP_DETAIL_FISNO: 'REQUEST_CARI_REPORT_SUB_GROUP_DETAIL_FISNO',
    SET_CARI_REPORT_SUB_GROUP_DETAIL_FISNO: 'SET_CARI_REPORT_SUB_GROUP_DETAIL_FISNO',
    CLEAR_CARI_REPORT_SUB_GROUP_DETAIL_FISNO: 'CLEAR_CARI_REPORT_SUB_GROUP_DETAIL_FISNO',
};
