export const reportConstants = {
    SET_FILTER_VALUES: 'SET_FILTER_VALUES',
    CLEAR_FILTER_VALUES: 'CLEAR_FILTER_VALUES',

    REQUEST_REPORT_PROJECT_CODES:'REQUEST_REPORT_PROJECT_CODES',
    SET_REPORT_PROJECT_CODES:'SET_REPORT_PROJECT_CODES',
    CLEAR_REPORT_PROJECT_CODES:'CLEAR_REPORT_PROJECT_CODES',

    REQUEST_PL_DASH_VALUES:'REQUEST_PL_DASH_VALUES',
    SET_PL_DASH_VALUES:'SET_PL_DASH_VALUES',
    CLEAR_PL_DASH_VALUES:'CLEAR_PL_DASH_VALUES',

    REQUEST_PL_REPORT_TABLE_VALUES:'REQUEST_PL_REPORT_TABLE_VALUES',
    SET_PL_REPORT_TABLE_VALUES:'SET_PL_REPORT_TABLE_VALUES',
    CLEAR_PL_REPORT_TABLE_VALUES:'CLEAR_PL_REPORT_TABLE_VALUES',

    REQUEST_PL_REPORT_MODAL_VALUES:'REQUEST_PL_REPORT_MODAL_VALUES',
    SET_PL_REPORT_MODAL_VALUES:'SET_PL_REPORT_MODAL_VALUES',
    CLEAR_PL_REPORT_MODAL_VALUES:'CLEAR_PL_REPORT_MODAL_VALUES',

    REQUEST_PIVOT_REPORT_VALUES:'REQUEST_PIVOT_REPORT_VALUES',
    SET_PIVOT_REPORT_VALUES:'SET_PIVOT_REPORT_VALUES',
    CLEAR_PIVOT_REPORT_VALUES:'CLEAR_PIVOT_REPORT_VALUES',

    REQUEST_PIVOT_REPORT_TEMPLATE_VALUES:'REQUEST_PIVOT_REPORT_TEMPLATE_VALUES',
    REQUEST_ADD_PIVOT_REPORT_TEMPLATE_VALUES:'REQUEST_ADD_PIVOT_REPORT_TEMPLATE_VALUES',
    REQUEST_UPDATE_PIVOT_REPORT_TEMPLATE_VALUES:'REQUEST_UPDATE_PIVOT_REPORT_TEMPLATE_VALUES',
    REQUEST_DELETE_PIVOT_REPORT_TEMPLATE_VALUES:'REQUEST_DELETE_PIVOT_REPORT_TEMPLATE_VALUES',
    SET_PIVOT_REPORT_TEMPLATE_VALUES:'SET_PIVOT_REPORT_TEMPLATE_VALUES',
    CLEAR_PIVOT_REPORT_TEMPLATE_VALUES:'CLEAR_PIVOT_REPORT_TEMPLATE_VALUES',

    SET_PIVOT_REPORT_TEMPLATE_APPLY_VALUES:'SET_PIVOT_REPORT_TEMPLATE_APPLY_VALUES',
    CLEAR_PIVOT_REPORT_TEMPLATE_APPLY_VALUES:'CLEAR_PIVOT_REPORT_TEMPLATE_APPLY_VALUES',
};
